# hugo.toml - Updated for Ananke Theme

baseURL = "https://your-domain.com/"  # آدرس دامنه خود را اینجا وارد کنید
languageCode = "en-us"
title = "Abolfazl Arzandi | Materials Engineer"
theme = "ananke" # <<<< نام قالب به ananke تغییر کرد

[params]
  # متن اصلی در بالای صفحه
  description = "Sophomore Materials & Metallurgy Engineering student at IUST. Passionate about research, continuous learning, and practical experience."
  
  # اطلاعات تماس در فوتر (پایین صفحه)
  favicon = ""
  site_logo = "" # می‌توانید لینک لوگو یا عکس خود را اینجا قرار دهید
  
  # اطلاعات شبکه های اجتماعی
  # نام هر فایل باید آیکون مربوط به آن در FontAwesome باشد
  [[params.social]]
    name = "linkedin"
    url = "https://linkedin.com/in/your-username"
  [[params.social]]
    name = "github"
    url = "https://github.com/your-username"
  [[params.social]]
    name = "envelope-o" # آیکون ایمیل
    url = "mailto:arzandi_abolfazl@metaleng.iust.ac.ir"