# hugo.toml - CORRECTED FOR HUGO MODULES

baseURL = "https://your-domain.com/"  # آدرس دامنه خود را اینجا وارد کنید
languageCode = "en-us"
title = "Abolfazl Arzandi | Materials Engineer"

# این بخش به هوگو می‌گوید که قالب را به صورت ماژول دانلود کند
[module]
  [[module.imports]]
    path = "github.com/theNewDynamic/gohugo-theme-ananke"

[params]
  description = "Sophomore Materials & Metallurgy Engineering student at IUST. Passionate about research, continuous learning, and practical experience."
  favicon = ""
  site_logo = ""
  
  [[params.social]]
    name = "linkedin"
    url = "https://linkedin.com/in/your-username"
  [[params.social]]
    name = "github"
    url = "https://github.com/your-username"
  [[params.social]]
    name = "envelope-o"
    url = "mailto:arzandi_abolfazl@metaleng.iust.ac.ir"