# hugo.toml - New configuration for Terminal theme

baseURL = "https://your-domain.com/"
languageCode = "en-us"
title = "Abolfazl Arzandi"

# THIS IS THE MOST IMPORTANT PART
theme = "terminal" 

[params]
  # این باعث می شود صفحه اصلی مستقیما محتوای شما را نشان دهد
  contentTypeName = "resume"
  
  # حذف بخش‌های اضافی
  showMenuItems = 2 # 1=hides, 2=shows
  fullWidthTheme = false
  centerTheme = true