# hugo.toml - SIMPLIFIED MANUAL THEME CONFIG

baseURL = "http://abulfazlarzandi.ir/"
languageCode = "en-us"
title = "Abolfazl Arzandi"
copyright = "© 2024 Abolfazl Arzandi"

# به جای ماژول، به صورت دستی به قالب اشاره می‌کنیم
theme = "blowfish" 

# این بخش‌ها برای نمایش صحیح رزومه هنوز لازم هستند
[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]

[markup.goldmark.renderer]
  unsafe = true

[params]
  author = "Abolfazl Arzandi"
  colorScheme = "blowfish"
  description = "Materials & Metallurgy Engineering Student | Passionate about Research & Technology"
  
  [[params.social]]
    name = "LinkedIn"
    url = "https://linkedin.com/in/your-username"
  [[params.social]]
    name = "GitHub"
    url = "https://github.com/your-username"
  [[params.social]]
    name = "Email"
    url = "mailto:arzandi_abolfazl@metaleng.iust.ac.ir"