# hugo.toml - THE CORRECT AND FINAL VERSION for Terminal Theme

baseURL = "https://your-domain.com/"
languageCode = "en-us"
title = "Abolfazl Arzandi's Resume"
theme = "terminal"

[params]
  contentTypeName = "resume"
  themeColor = "blue"
  showMenuItems = 1
  fullWidthTheme = false
  centerTheme = true

  # این ساختار صحیح لوگو است که قالب انتظار دارد
  # به جای یک متن ساده، یک "جدول" از پارامترهاست
  [params.logo]
    logoText = "Abolfazl Arzandi"
    logoHomeLink = "/"

  # این بخش فوتر را به طور کامل و به روش صحیح حذف می‌کند
  [params.footer]
    showCopyright = false
    showThemeAttribution = false
    showHackerAttribution = false