# hugo.toml - FINAL & PERFECTED for BLOWFISH THEME

baseURL = "http://abulfazlarzandi.ir/"  # لطفاً آدرس دامنه خود را اینجا وارد کنید
languageCode = "en-us"
title = "Abolfazl Arzandi"
copyright = "© 2024 Abolfazl Arzandi"

# این بخش قالب Blowfish را به صورت ماژول نصب می‌کند
[module]
  [module.hugoVersion]
    extended = true
    min = "0.111.0"
  [[module.imports]]
    path = "github.com/nunocoracao/blowfish"

# ======================================================
# این مهم‌ترین بخش برای نمایش رزومه شما در مرکز صفحه است
# ======================================================
[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]

[markup.goldmark.renderer]
  unsafe = true # لازم برای رندر کردن HTML در markdown

[params]
  # تنظیمات کلی ظاهر
  mainSections = ["posts"]
  author = "Abolfazl Arzandi"
  colorScheme = "blowfish" # حالت پیش‌فرض، می‌توانید به dark یا light تغییر دهید
  description = "Materials & Metallurgy Engineering Student | Passionate about Research & Technology"

  # لینک شبکه‌های اجتماعی
  [[params.social]]
    name = "LinkedIn"
    url = "https://linkedin.com/in/your-username"
  [[params.social]]
    name = "GitHub"
    url = "https://github.com/your-username"
  [[params.social]]
    name = "Email"
    url = "mailto:arzandi_abolfazl@metaleng.iust.ac.ir"

# منو را خالی می گذاریم تا ظاهری کاملاً مینیمال داشته باشد
[menu]
  [[menu.main]]

# تنظیمات مربوط به طرح‌بندی (Layout)
[per-section]
  posts = "single"